name: enova_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  hive: ^2.2.3
  flutter_rating_bar: ^4.0.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_database: ^11.3.5
  firebase_storage: ^12.2.0
  uuid: ^4.3.1
  flutter_quill: ^11.4.0
  flutter_quill_extensions: ^11.0.0
  animated_text_kit: ^4.2.3
  flutter_facebook_auth: ^6.0.4
  google_sign_in: ^6.3.0
  flutter_signin_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
